spring.application.name=inventarios
# Conexion con MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/inventario_db?createDatabaseIfNotExist=True
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Configurar el patron del log (en lugar de logback-spring.xml)
logging.pattern.console=[%thread] %-5level: %logger - %msg%n

# Configurar el nivel de log (INFO para este caso)
logging.level.root=INFO
#Opcional, configurar niveles por paquetes
logging.level.curso.inventarios=DEBUG
logging.level.org.springframework=WARN

#Cambiar el puerto del servidor Tomcat
#server.port=8080
spring.main.banner-mode=off
